# Generated by Django 3.2 on 2023-09-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenaSquaredApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=1234, max_length=254),
            preserve_default=False,
        ),
    ]
